language: node_js
node_js:
  - 8.10.0
notifications:
  email: false

cache:
  directories:
    - node_modules

services:
  - postgresql

env:
  - NODE_ENV=test DB_USERNAME=askit DB_PASSWORD=password
before_script:
  - psql -c 'drop database if exists weconnect_test;' -U postgres
  - psql -c 'create database weconnect_test;' -U postgres
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
  - npm run coveralls