language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
    - node_modules

services:
  - postgresql

env:
  - NODE_ENV=test DB_USERNAME=askit DB_PASSWORD=password JWT_SECRET=secret

before_script:
  - npm i nyc dotenv --save
  - psql -c 'create database weconnect_api_test;' -U postgres
  - psql -c "CREATE USER askit WITH PASSWORD 'password';" -U postgres

script:
  - npm test

after_success:
  - npm run coverage
  - npm run coveralls
