language: node_js
node_js:
  - 8.10.0
notifications:
  email: false

cache:
  directories:
    - node_modules

services:
  - postgresql

before_script:
  - psql -c 'drop database if exists weconnect_test;' -U postgres
  - psql -c 'create database weconnect_test;' -U postgres
  - npm install
  - npm update bcrypt

script:
  - npm test

after_success:
  - npm run coverage
  - npm run coveralls

addons:
 postgresql: "9.6"